- name: Install packages
  apt: name={{item}}
  with_items:
    - nano
    - tlp
    - tlp-rdw
    - tp-smapi-dkms
    - acpi-call-dkms
    - thermald
    - network-manager-vpnc
    - network-manager-vpnc-gnome
    - vpnc
    - python-pip

- name: install atom
  command: snap install atom --classic

- name: install kubectl
  command: snap install kubectl --classic

- name: install spotify
  command: snap install spotify

- name: install telegram
  command: snap install telegram-desktop

- name: install awscli
  command: creates="~/.local/bin/aws" pip install awscli --upgrade --user
  become: yes
  become_user: andrew
